name: Github Actions Runner

on:
  push:
    branches:
      - "main"
  schedule:
    - cron:  '00 10 * * 1'   # once a week on a monday

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USERNAME: ${{ vars.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      DOCKER_REGISTRY_NAME: ${{ vars.DOCKER_REGISTRY_NAME }}
      DOCKER_REGISTRY_URL: ${{ vars.DOCKER_REGISTRY_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
            envkey_PASSWORD_ONE: ${{ secrets.PASSWORD_ONE }}
            envkey_PASSWORD_TWO: ${{ secrets.PASSWORD_TWO }}
            envkey_PASSWORD_THREE: ${{ secrets.PASSWORD_THREE }}
            envkey_PASSWORD_FOUR: ${{ secrets.PASSWORD_FOUR }}
            envkey_PASSWORD_FIVE: ${{ secrets.PASSWORD_FIVE }}
            envkey_PASSWORD_SIX: ${{ secrets.PASSWORD_SIX }}
            envkey_PASSWORD_SEVEN: ${{ secrets.PASSWORD_SEVEN }}
            envkey_PASSWORD_EIGHT: ${{ secrets.PASSWORD_SEVEN }}
            envkey_PASSWORD_NINE: ${{ secrets.PASSWORD_SEVEN }}
            envkey_SUPABASE_PG_PASSWORD: ${{ secrets.SUPABASE_PG_PASSWORD }}
            envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            envkey_HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
#            envkey_VARIABLE: ${{ vars.SOME_ACTION_VARIABLE }}
            directory: .
            file_name: .env
            fail_on_empty: false
            sort_keys: false
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Docker Build & Push
        run: |
          make ci-docker-build
          make ci-docker-push