name: CI Runner

on:
  push:
    branches:
      - "*"
  schedule:
    - cron:  '00 10 * * 1'   # once a week on a monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --dev
      - name: Check linting
        run: |
          make ci-lint
      - name: Check tests
        run: |
          make ci-test
        env:
          OPENAI_API_KEY: ""
          HUGGINGFACE_API_KEY: ""
          PYTEST_CURRENT_TEST: "true"
