name: Github Actions Runner

on:
  push:
    branches:
      - "*"
  schedule:
    - cron:  '00 10 * * 1'   # once a week on a monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check linting
        run: |
          make ci-lint
      - name: Check semgrep
        run: |
          make ci-semgrep
      - name: Check tests
        run: |
          make ci-test